services:
  - type: web
    name: selenium-image-extractor
    env: docker
    plan: free   # change to starter/standard if needed
    region: singapore   # or oregon, frankfurt
    dockerfilePath: Dockerfile
    autoDeploy: true

    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_PORT
        value: "8501"
